// Code generated by vexctl clientgen — DO NOT EDIT.
// Source: AuthService smithy model.

package auth

import (
	"net/http"
	"time"
)

// Client is the typed SDK for AuthService.
//
// Construct with New(); every operation is a typed method on Client.
// Default HTTPClient has a 30s timeout and follows redirects; override
// with WithHTTPClient(...) when you need different behavior.
type Client struct {
	endpoint string
	token    string
	http     *http.Client
}

// Option configures a Client at construction time.
type Option func(*Client)

// WithHTTPClient overrides the default http.Client. Use this to plug in
// custom transports, retry middleware, or test doubles.
func WithHTTPClient(h *http.Client) Option {
	return func(c *Client) { c.http = h }
}

// WithTimeout sets the per-request timeout on the default http.Client.
// Ignored if WithHTTPClient already supplied a fully-configured client.
func WithTimeout(d time.Duration) Option {
	return func(c *Client) {
		if c.http == nil {
			c.http = &http.Client{Timeout: d}
		} else {
			c.http.Timeout = d
		}
	}
}

// New constructs a Client. endpoint is the service base URL (e.g.
// "http://vex-vault:8200"); token is the bearer credential sent on every
// request. Either may be empty for tests against httptest.NewServer.
func New(endpoint, token string, opts ...Option) *Client {
	c := &Client{
		endpoint: endpoint,
		token:    token,
		http:     &http.Client{Timeout: 30 * time.Second},
	}
	for _, o := range opts {
		o(c)
	}
	if c.endpoint == "" {
		c.endpoint = ""
	}
	return c
}

// Endpoint returns the service base URL the client is targeting.
func (c *Client) Endpoint() string { return c.endpoint }
