// Code generated by vexctl clientgen — DO NOT EDIT.
// Source: AuthService smithy model.

// Package auth is the typed Go SDK for AuthService.
//
// Usage:
//
//	c := auth.New("", "<bearer-token>")
//	out, err := c.OperationName(ctx, auth.OperationNameInput{...})
//	if err != nil {
//	    var nf auth.ErrorEnvelope
//	    if errors.As(err, &nf) { ... typed error ... }
//	}
//
// The SDK shares its wire types with the server's generated handlers by
// construction — both sides emit from the same Smithy spec, so they cannot
// drift apart. Add new operations to the .smithy and regenerate both halves.
package auth
