// Code generated by vexctl clientgen — DO NOT EDIT.
// Source: AuthService smithy model.

package auth

import (
	"encoding/json"
	"errors"
	"io"
	"net/http"
)

// ErrorEnvelope is the wire shape every server returns on error.
type ErrorEnvelope struct {
	Code      string         `json:"code"`
	Message   string         `json:"message"`
	RequestID string         `json:"request_id,omitempty"`
	TraceID   string         `json:"trace_id,omitempty"`
	Details   map[string]any `json:"details,omitempty"`
	// Status is the HTTP status code observed on the wire. Not part of the
	// JSON shape; set by the decoder so callers can switch on it.
	Status int `json:"-"`
}

func (e ErrorEnvelope) Error() string {
	if e.Code != "" && e.Message != "" {
		return e.Code + ": " + e.Message
	}
	if e.Message != "" {
		return e.Message
	}
	return "unknown error"
}

// Sentinel errors callers can match with errors.Is. Decoded from
// ErrorEnvelope.Code on every non-2xx response.
var (
	ErrValidation   = errors.New("validation failed")
	ErrUnauthorized = errors.New("unauthorized")
	ErrForbidden    = errors.New("forbidden")
	ErrNotFound     = errors.New("not found")
	ErrConflict     = errors.New("conflict")
	ErrInternal     = errors.New("internal error")
)

// decodeError reads an HTTP response into an ErrorEnvelope and joins it with
// the matching sentinel so both errors.As(&env) and errors.Is(sentinel) work.
func decodeError(resp *http.Response) error {
	var env ErrorEnvelope
	body, _ := io.ReadAll(resp.Body)
	_ = json.Unmarshal(body, &env)
	env.Status = resp.StatusCode
	sentinel := sentinelFor(env.Code, resp.StatusCode)
	if sentinel != nil {
		return errors.Join(env, sentinel)
	}
	return env
}

func sentinelFor(code string, status int) error {
	switch code {
	case "VALIDATION_FAILED":
		return ErrValidation
	case "UNAUTHORIZED":
		return ErrUnauthorized
	case "FORBIDDEN":
		return ErrForbidden
	case "NOT_FOUND":
		return ErrNotFound
	case "CONFLICT":
		return ErrConflict
	case "INTERNAL_ERROR":
		return ErrInternal
	}
	// Fallback: bucket by HTTP status when the server emitted a typed code
	// that doesn't match a sentinel (e.g. "VaultNotFound" → ErrNotFound).
	switch status {
	case http.StatusBadRequest:
		return ErrValidation
	case http.StatusUnauthorized:
		return ErrUnauthorized
	case http.StatusForbidden:
		return ErrForbidden
	case http.StatusNotFound:
		return ErrNotFound
	case http.StatusConflict, http.StatusUnprocessableEntity:
		return ErrConflict
	}
	return nil
}
