// Code generated by vexctl clientgen — DO NOT EDIT.
// Source: AuthService smithy model.

package auth

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
)

// keep imports referenced when only some are needed.
var (
	_ = bytes.NewReader
	_ = context.Background
	_ = json.NewDecoder
	_ = fmt.Sprintf
	_ = io.EOF
	_ = http.NewRequestWithContext
	_ = url.PathEscape
)

// AssumeRole calls POST /auth/assume-role.
func (c *Client) AssumeRole(ctx context.Context, in AssumeRoleInput) (AssumeRoleOutput, error) {
	var zero AssumeRoleOutput
	path := "/auth/assume-role"
	u := c.endpoint + path

	var bodyReader io.Reader
	body, err := json.Marshal(in)
	if err != nil {
		return zero, fmt.Errorf("AssumeRole: marshal body: %w", err)
	}
	bodyReader = bytes.NewReader(body)

	req, err := http.NewRequestWithContext(ctx, "POST", u, bodyReader)
	if err != nil {
		return zero, fmt.Errorf("AssumeRole: new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return zero, fmt.Errorf("AssumeRole: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return zero, decodeError(resp)
	}
	if resp.StatusCode == http.StatusNoContent {
		return zero, nil
	}
	var out AssumeRoleOutput
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return zero, fmt.Errorf("AssumeRole: decode response: %w", err)
	}
	return out, nil
}

// CreateServiceAccount calls POST /auth/service-accounts.
func (c *Client) CreateServiceAccount(ctx context.Context, in CreateServiceAccountInput) (CreateServiceAccountOutput, error) {
	var zero CreateServiceAccountOutput
	path := "/auth/service-accounts"
	u := c.endpoint + path

	var bodyReader io.Reader
	body, err := json.Marshal(in)
	if err != nil {
		return zero, fmt.Errorf("CreateServiceAccount: marshal body: %w", err)
	}
	bodyReader = bytes.NewReader(body)

	req, err := http.NewRequestWithContext(ctx, "POST", u, bodyReader)
	if err != nil {
		return zero, fmt.Errorf("CreateServiceAccount: new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return zero, fmt.Errorf("CreateServiceAccount: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return zero, decodeError(resp)
	}
	if resp.StatusCode == http.StatusNoContent {
		return zero, nil
	}
	var out CreateServiceAccountOutput
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return zero, fmt.Errorf("CreateServiceAccount: decode response: %w", err)
	}
	return out, nil
}

// DeleteServiceAccount calls DELETE /auth/service-accounts/{clientId}.
func (c *Client) DeleteServiceAccount(ctx context.Context, in ServiceAccountIdInput) error {
	path := fmt.Sprintf("/auth/service-accounts/%s", url.PathEscape(in.ClientId))
	u := c.endpoint + path

	var bodyReader io.Reader

	req, err := http.NewRequestWithContext(ctx, "DELETE", u, bodyReader)
	if err != nil {
		return fmt.Errorf("DeleteServiceAccount: new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("DeleteServiceAccount: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return decodeError(resp)
	}
	return nil
}

// GetHealth calls GET /health.
func (c *Client) GetHealth(ctx context.Context) (HealthOutput, error) {
	var zero HealthOutput
	path := "/health"
	u := c.endpoint + path

	var bodyReader io.Reader

	req, err := http.NewRequestWithContext(ctx, "GET", u, bodyReader)
	if err != nil {
		return zero, fmt.Errorf("GetHealth: new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return zero, fmt.Errorf("GetHealth: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return zero, decodeError(resp)
	}
	if resp.StatusCode == http.StatusNoContent {
		return zero, nil
	}
	var out HealthOutput
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return zero, fmt.Errorf("GetHealth: decode response: %w", err)
	}
	return out, nil
}

// GetJWKS calls GET /.well-known/jwks.json.
func (c *Client) GetJWKS(ctx context.Context) (JWKSet, error) {
	var zero JWKSet
	path := "/.well-known/jwks.json"
	u := c.endpoint + path

	var bodyReader io.Reader

	req, err := http.NewRequestWithContext(ctx, "GET", u, bodyReader)
	if err != nil {
		return zero, fmt.Errorf("GetJWKS: new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return zero, fmt.Errorf("GetJWKS: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return zero, decodeError(resp)
	}
	if resp.StatusCode == http.StatusNoContent {
		return zero, nil
	}
	var out JWKSet
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return zero, fmt.Errorf("GetJWKS: decode response: %w", err)
	}
	return out, nil
}

// GetOpenIDConfiguration calls GET /.well-known/openid-configuration.
func (c *Client) GetOpenIDConfiguration(ctx context.Context) (OpenIDConfiguration, error) {
	var zero OpenIDConfiguration
	path := "/.well-known/openid-configuration"
	u := c.endpoint + path

	var bodyReader io.Reader

	req, err := http.NewRequestWithContext(ctx, "GET", u, bodyReader)
	if err != nil {
		return zero, fmt.Errorf("GetOpenIDConfiguration: new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return zero, fmt.Errorf("GetOpenIDConfiguration: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return zero, decodeError(resp)
	}
	if resp.StatusCode == http.StatusNoContent {
		return zero, nil
	}
	var out OpenIDConfiguration
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return zero, fmt.Errorf("GetOpenIDConfiguration: decode response: %w", err)
	}
	return out, nil
}

// GetServiceAccount calls GET /auth/service-accounts/{clientId}.
func (c *Client) GetServiceAccount(ctx context.Context, in ServiceAccountIdInput) (ServiceAccount, error) {
	var zero ServiceAccount
	path := fmt.Sprintf("/auth/service-accounts/%s", url.PathEscape(in.ClientId))
	u := c.endpoint + path

	var bodyReader io.Reader

	req, err := http.NewRequestWithContext(ctx, "GET", u, bodyReader)
	if err != nil {
		return zero, fmt.Errorf("GetServiceAccount: new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return zero, fmt.Errorf("GetServiceAccount: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return zero, decodeError(resp)
	}
	if resp.StatusCode == http.StatusNoContent {
		return zero, nil
	}
	var out ServiceAccount
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return zero, fmt.Errorf("GetServiceAccount: decode response: %w", err)
	}
	return out, nil
}

// GetSession calls GET /auth/sessions/{sessionId}.
func (c *Client) GetSession(ctx context.Context, in SessionIdInput) (SessionDetail, error) {
	var zero SessionDetail
	path := fmt.Sprintf("/auth/sessions/%s", url.PathEscape(in.SessionId))
	u := c.endpoint + path

	var bodyReader io.Reader

	req, err := http.NewRequestWithContext(ctx, "GET", u, bodyReader)
	if err != nil {
		return zero, fmt.Errorf("GetSession: new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return zero, fmt.Errorf("GetSession: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return zero, decodeError(resp)
	}
	if resp.StatusCode == http.StatusNoContent {
		return zero, nil
	}
	var out SessionDetail
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return zero, fmt.Errorf("GetSession: decode response: %w", err)
	}
	return out, nil
}

// IssueToken calls POST /auth/token.
func (c *Client) IssueToken(ctx context.Context, in TokenRequest) (TokenResponse, error) {
	var zero TokenResponse
	path := "/auth/token"
	u := c.endpoint + path

	var bodyReader io.Reader
	body, err := json.Marshal(in)
	if err != nil {
		return zero, fmt.Errorf("IssueToken: marshal body: %w", err)
	}
	bodyReader = bytes.NewReader(body)

	req, err := http.NewRequestWithContext(ctx, "POST", u, bodyReader)
	if err != nil {
		return zero, fmt.Errorf("IssueToken: new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return zero, fmt.Errorf("IssueToken: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return zero, decodeError(resp)
	}
	if resp.StatusCode == http.StatusNoContent {
		return zero, nil
	}
	var out TokenResponse
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return zero, fmt.Errorf("IssueToken: decode response: %w", err)
	}
	return out, nil
}

// ListServiceAccounts calls GET /auth/service-accounts.
func (c *Client) ListServiceAccounts(ctx context.Context, in ListServiceAccountsInput) (ListServiceAccountsOutput, error) {
	var zero ListServiceAccountsOutput
	path := "/auth/service-accounts"
	u := c.endpoint + path
	q := url.Values{}
	if in.Tenant != "" {
		q.Set("tenant", in.Tenant)
	}
	if encoded := q.Encode(); encoded != "" {
		u += "?" + encoded
	}

	var bodyReader io.Reader

	req, err := http.NewRequestWithContext(ctx, "GET", u, bodyReader)
	if err != nil {
		return zero, fmt.Errorf("ListServiceAccounts: new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return zero, fmt.Errorf("ListServiceAccounts: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return zero, decodeError(resp)
	}
	if resp.StatusCode == http.StatusNoContent {
		return zero, nil
	}
	var out ListServiceAccountsOutput
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return zero, fmt.Errorf("ListServiceAccounts: decode response: %w", err)
	}
	return out, nil
}

// Login calls POST /auth/login.
func (c *Client) Login(ctx context.Context, in LoginInput) (LoginOutput, error) {
	var zero LoginOutput
	path := "/auth/login"
	u := c.endpoint + path

	var bodyReader io.Reader
	body, err := json.Marshal(in)
	if err != nil {
		return zero, fmt.Errorf("Login: marshal body: %w", err)
	}
	bodyReader = bytes.NewReader(body)

	req, err := http.NewRequestWithContext(ctx, "POST", u, bodyReader)
	if err != nil {
		return zero, fmt.Errorf("Login: new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return zero, fmt.Errorf("Login: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return zero, decodeError(resp)
	}
	if resp.StatusCode == http.StatusNoContent {
		return zero, nil
	}
	var out LoginOutput
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return zero, fmt.Errorf("Login: decode response: %w", err)
	}
	return out, nil
}

// Logout calls POST /auth/logout.
func (c *Client) Logout(ctx context.Context, in LogoutInput) error {
	path := "/auth/logout"
	u := c.endpoint + path

	var bodyReader io.Reader
	body, err := json.Marshal(in)
	if err != nil {
		return fmt.Errorf("Logout: marshal body: %w", err)
	}
	bodyReader = bytes.NewReader(body)

	req, err := http.NewRequestWithContext(ctx, "POST", u, bodyReader)
	if err != nil {
		return fmt.Errorf("Logout: new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("Logout: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return decodeError(resp)
	}
	return nil
}

// RefreshSession calls POST /auth/refresh.
func (c *Client) RefreshSession(ctx context.Context, in RefreshInput) (LoginOutput, error) {
	var zero LoginOutput
	path := "/auth/refresh"
	u := c.endpoint + path

	var bodyReader io.Reader
	body, err := json.Marshal(in)
	if err != nil {
		return zero, fmt.Errorf("RefreshSession: marshal body: %w", err)
	}
	bodyReader = bytes.NewReader(body)

	req, err := http.NewRequestWithContext(ctx, "POST", u, bodyReader)
	if err != nil {
		return zero, fmt.Errorf("RefreshSession: new request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	resp, err := c.http.Do(req)
	if err != nil {
		return zero, fmt.Errorf("RefreshSession: http do: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return zero, decodeError(resp)
	}
	if resp.StatusCode == http.StatusNoContent {
		return zero, nil
	}
	var out LoginOutput
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return zero, fmt.Errorf("RefreshSession: decode response: %w", err)
	}
	return out, nil
}
