// Code generated by vexctl clientgen — DO NOT EDIT.
// Source: AuthService smithy model.

package auth

// AssumeRoleInput mirrors the Smithy structure of the same name.
type AssumeRoleInput struct {
	RoleSlug        string `json:"role_slug"`
	SessionName     string `json:"session_name,omitempty"`
	DurationSeconds int    `json:"duration_seconds,omitempty"`
}

// AssumeRoleOutput mirrors the Smithy structure of the same name.
type AssumeRoleOutput struct {
	AccessToken   string         `json:"access_token"`
	ExpiresAt     string         `json:"expires_at"`
	AssumedClaims *AssumedClaims `json:"assumed_claims"`
}

// AssumedClaims mirrors the Smithy structure of the same name.
type AssumedClaims struct {
	Iss         string `json:"iss"`
	Sub         string `json:"sub"`
	Exp         int64  `json:"exp"`
	Iat         int64  `json:"iat"`
	Tenant      string `json:"tenant"`
	Role        string `json:"role"`
	AssumedBy   string `json:"assumed_by"`
	SessionName string `json:"session_name,omitempty"`
}

// CreateServiceAccountInput mirrors the Smithy structure of the same name.
type CreateServiceAccountInput struct {
	ClientId    string   `json:"client_id"`
	Name        string   `json:"name"`
	Tenant      string   `json:"tenant"`
	Description string   `json:"description,omitempty"`
	Scope       []string `json:"scope,omitempty"`
}

// CreateServiceAccountOutput mirrors the Smithy structure of the same name.
type CreateServiceAccountOutput struct {
	ClientId     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	Name         string `json:"name"`
	Tenant       string `json:"tenant"`
}

// HealthOutput mirrors the Smithy structure of the same name.
type HealthOutput struct {
	Status string `json:"status"`
}

// JWK mirrors the Smithy structure of the same name.
type JWK struct {
	Kty string `json:"kty"`
	Use string `json:"use"`
	Alg string `json:"alg"`
	Kid string `json:"kid"`
	N   string `json:"n,omitempty"`
	E   string `json:"e,omitempty"`
	X   string `json:"x,omitempty"`
	Y   string `json:"y,omitempty"`
	Crv string `json:"crv,omitempty"`
}

// JWKSet mirrors the Smithy structure of the same name.
type JWKSet struct {
	Keys []*JWK `json:"keys"`
}

// ListServiceAccountsInput mirrors the Smithy structure of the same name.
type ListServiceAccountsInput struct {
	Tenant string `json:"tenant,omitempty"`
}

// ListServiceAccountsOutput mirrors the Smithy structure of the same name.
type ListServiceAccountsOutput struct {
	Accounts []*ServiceAccount `json:"accounts"`
}

// LoginInput mirrors the Smithy structure of the same name.
type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Tenant   string `json:"tenant,omitempty"`
}

// LoginOutput mirrors the Smithy structure of the same name.
type LoginOutput struct {
	SessionId string   `json:"session_id"`
	Token     string   `json:"token"`
	ExpiresAt string   `json:"expires_at"`
	Tenant    string   `json:"tenant"`
	Roles     []string `json:"roles,omitempty"`
}

// LogoutInput mirrors the Smithy structure of the same name.
type LogoutInput struct {
	SessionId string `json:"session_id"`
}

// OpenIDConfiguration mirrors the Smithy structure of the same name.
type OpenIDConfiguration struct {
	Issuer                           string   `json:"issuer"`
	AuthorizationEndpoint            string   `json:"authorization_endpoint"`
	TokenEndpoint                    string   `json:"token_endpoint"`
	JwksUri                          string   `json:"jwks_uri"`
	ResponseTypesSupported           []string `json:"response_types_supported"`
	SubjectTypesSupported            []string `json:"subject_types_supported"`
	IdTokenSigningAlgValuesSupported []string `json:"id_token_signing_alg_values_supported"`
	GrantTypesSupported              []string `json:"grant_types_supported,omitempty"`
	ScopesSupported                  []string `json:"scopes_supported,omitempty"`
}

// RefreshInput mirrors the Smithy structure of the same name.
type RefreshInput struct {
	SessionId string `json:"session_id"`
}

// RevokeTokenRequest mirrors the Smithy structure of the same name.
type RevokeTokenRequest struct {
	Token         string `json:"token"`
	TokenTypeHint string `json:"token_type_hint,omitempty"`
}

// RevokeTokenResponse mirrors the Smithy structure of the same name.
type RevokeTokenResponse struct {
}

// ServiceAccount mirrors the Smithy structure of the same name.
type ServiceAccount struct {
	ClientId    string   `json:"client_id"`
	Name        string   `json:"name"`
	Tenant      string   `json:"tenant"`
	Description string   `json:"description,omitempty"`
	Scope       []string `json:"scope,omitempty"`
	CreatedAt   string   `json:"created_at"`
}

// ServiceAccountIdInput mirrors the Smithy structure of the same name.
type ServiceAccountIdInput struct {
	ClientId string `json:"client_id"`
}

// ServiceClaims mirrors the Smithy structure of the same name.
type ServiceClaims struct {
	Iss      string   `json:"iss"`
	Sub      string   `json:"sub"`
	Aud      []string `json:"aud"`
	Exp      int64    `json:"exp"`
	Iat      int64    `json:"iat"`
	Tenant   string   `json:"tenant"`
	Roles    []string `json:"roles,omitempty"`
	Scope    []string `json:"scope,omitempty"`
	ClientId string   `json:"client_id,omitempty"`
}

// SessionDetail mirrors the Smithy structure of the same name.
type SessionDetail struct {
	SessionId string   `json:"session_id"`
	Subject   string   `json:"subject"`
	Tenant    string   `json:"tenant"`
	IssuedAt  string   `json:"issued_at"`
	ExpiresAt string   `json:"expires_at"`
	Roles     []string `json:"roles,omitempty"`
}

// SessionIdInput mirrors the Smithy structure of the same name.
type SessionIdInput struct {
	SessionId string `json:"session_id"`
}

// SignUpInput mirrors the Smithy structure of the same name.
type SignUpInput struct {
	CompanyName string `json:"company_name"`
	Tenant      string `json:"tenant"`
	Username    string `json:"username"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	DisplayName string `json:"display_name,omitempty"`
}

// SignUpOutput mirrors the Smithy structure of the same name.
type SignUpOutput struct {
	Tenant           string   `json:"tenant"`
	Username         string   `json:"username"`
	AccessToken      string   `json:"access_token"`
	TokenType        string   `json:"token_type"`
	ExpiresIn        int      `json:"expires_in"`
	ProvisionedRoles []string `json:"provisioned_roles"`
	RootRole         string   `json:"root_role"`
}

// TokenRequest mirrors the Smithy structure of the same name.
type TokenRequest struct {
	GrantType    string   `json:"grant_type"`
	ClientId     string   `json:"client_id,omitempty"`
	ClientSecret string   `json:"client_secret,omitempty"`
	Username     string   `json:"username,omitempty"`
	Password     string   `json:"password,omitempty"`
	RefreshToken string   `json:"refresh_token,omitempty"`
	Tenant       string   `json:"tenant,omitempty"`
	Scope        []string `json:"scope,omitempty"`
}

// TokenResponse mirrors the Smithy structure of the same name.
type TokenResponse struct {
	AccessToken           string   `json:"access_token"`
	TokenType             string   `json:"token_type"`
	ExpiresIn             int      `json:"expires_in"`
	RefreshToken          string   `json:"refresh_token,omitempty"`
	RefreshTokenExpiresIn int      `json:"refresh_token_expires_in,omitempty"`
	Scope                 []string `json:"scope,omitempty"`
}
